---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: ishaqmd/petclinic:latest
	resources:
      	  requests:
            memory: "1000Mi"
            cpu: "1000m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
	ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
	type: NodePort
    app: petclinic
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  externalIPs:
    - 34.125.7.73
