global:

  scrape_interval: 15s

  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'

    static_configs:

    - targets: ['34.125.168.128:9090']

      labels:

        alias: 'prometheus'

  - job_name: 'cadvisor'

    static_configs:

    - targets: ['34.125.168.128:8081']

      labels:

        alias: 'cadvisor'

  - job_name: 'node-exporter'

    static_configs:

    - targets: ['34.125.168.128:9100']

      labels:

        alias: 'node-exporter'
        
  - job_name: 'petclinic'

    static_configs:

    - targets: ['34.125.168.128:8080']

      labels:

        alias: 'petclinic'
